# This is a basic workflow to help you get started with Actions

name: merge

# Controls when the action will run. 
on:

  pull_request:
    branches: [ main ]
    types: [opened,synchronize,closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: hmarr/debug-action@v2
      - name: See merge commit sha and if merged
        run: |
          echo ${{ github.event.pull_request.merge_commit_sha }}
          echo ${{ github.event.pull_request.merged }}
      
    
